name: Generate and Deploy Docs

on:
  workflow_call:
    inputs:
      doc_target:
        required: true
        type: string
      extra-cmake-options:
        required: false
        type: string
        default: ""
      extra-install:
        required: false
        type: string
        default: ""
      docs_source_dir:
        required: false
        type: string
        default: "./docs"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stormbytepp/githubactions/generate-doc@master
        with:
          doc_target: ${{ inputs.doc_target }}
          extra-cmake-options: ${{ inputs.extra-cmake-options }}
          extra-install: ${{ inputs.extra-install }}
          docs_source_dir: ${{ inputs.docs_source_dir }}

  deploy:
    runs-on: ubuntu-latest
    needs: generate-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
